[project]
name = "mcp-faq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.13.0.1",
    "minsearch>=0.0.7",
    "requests>=2.32.5",
    "toyaikit>=0.0.5",
]
